name: workflow

on: 
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v1
      with: { go-version: 1.14 }

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1 
      with: { terraform_version: 0.12.24 }

    - name: Install Taskfile
      run: curl -sL https://taskfile.dev/install.sh | sh

    - name: Run tests
      run: ./bin/task test
